### PR TITLE
Add 3.0

### PR DESCRIPTION
**Pull request by Ailrun**

### CODE REVIEW

**Comment by LinusU** [comment]
ping @andy-ms, any chance of getting this merged? ☺️ 

I think it's needed for DefinitelyTyped/DefinitelyTyped#28001

**Comment by SamHH** [comment]
Yep, AFAIK it's needed for any DT type defs that are to require 3.0+. Similar limitation with react-copy-write typings.

**Comment by andy-ms** [comment]
We typically don't allow a new TypeScript version on DT until it's been out for at least a month.

**Comment by SamHH** [comment]
I'm curious, what's the reasoning behind that @andy-ms?

**Comment by andy-ms** [comment]
Most people don't upgrade TypeScript the day of an update. But many people don't lock their dependencies (Microsoft/TypeScript-Handbook#807) so they would be broken when their types packages updated. Ideally people who have a locked-down TS version would have locked-down types packages, but in practice many don't. The month waiting period gives them time to update.

**Comment by Ailrun** [comment]
@andy-ms then will this PR merged in September? or is that literally `at least` a month after (so that takes more time before merging this)

**Comment by andy-ms** [comment]
Yes, though note that changes to popular packages like `@types/node` and `@types/express` may still be rejected if the changes don't seem to be worth the upgrade, like changing a single `any` to `unknown`.

**Comment by andy-ms** [comment]
@Ailrun What are you using dtslint for? If you wrote the package in TS you should be able to use the [`--declaration`](https://www.typescriptlang.org/docs/handbook/compiler-options.html) compiler option.

**Comment by Ailrun** [comment]
@andy-ms To use something like `//$ExpectType` and `//$ExpectError` ... well, it's good for type test, isn't it?

**Comment by thw0rted** [comment]
If you're collecting data points, I just [submitted a new DT package](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/28074) where I had to include a TODO comment to the effect that the typings are incomplete until 3.0 support lands.  The module I'm describing has a generic that returns a function whose call parameters are based on the parameters of a function passed to it, in other words, `foo((x: number, y: string, z: boolean) => number)` returns an object  whose `bar` method takes a number, string, and boolean, and returns a number.  3.0 allows me to describe this using Generic Rest Parameters; I'm not sure it's possible otherwise.

**Comment by Ailrun** [comment]
@thw0rted I'm just curious, doesn't `foo<F extends (...args: any[]) => any>(f: F): { bar: F }` work?

**Comment by thw0rted** [comment]
I misspoke, the returned method has the same arguments but a different return type -- you're right, if it was the exact same signature, it could be passed through.

**Comment by dbellizzi** [comment]
I'm also using dtslint for internal type tests and would love to see this land for 3.0 support.  It actually supported testing with 3.0 when `next` pointed to 3.0, but now that `next` points to 3.1, there's no way to get 3.0 tests running.

Separately, 3.1 `next` tests fail because errors are reported on different lines now, so I'm curious how this is going to be supported across the change.

**Comment by Ailrun** [comment]
@andy-ms is there any situation changed?

**Comment by m93a** [comment]
TypeScript version 3.0 supports generic rest parameters which can't be documented well in any of the previous version. Example from `markdown-it`:

```typescript
use<T extends any[] = any[]>(
    plugin: (md: MarkdownIt, ...params: T) => void,
    ...params: T
): MarkdownIt;
```

This automatically infers `T` as a tuple and correctly matches the argument types. The closest thing you can do in previous versions is this:

```typescript
use<T extends any = any>(
    plugin: (md: MarkdownIt, ...params: T[]) => void,
    ...params: T[]
): MarkdownIt;
```

But such declaration doesn't infer anything at all, supports only parameters of the same types and ultimately cripples the usability in 3.0. It's a pitty there isn't a good fallback for older versions, but I think we should keep moving forwards and prefer good typing over support for unupdated editors.

**Comment by mmiszy** [comment]
Any chances of getting this merged?

**Comment by Ailrun** [comment]
@dbellizzi is right. I close this by fef4df5.

**Pull request closed without merging**
