### PR TITLE
Support header line “Minimum TypeScript Version”

### PR DESCRIPTION
**Pull request by andrewbranch**
People are _constantly_ confused about the `TypeScript Version:` header line and instinctively update it to be the latest TypeScript version. This PR allows the word `Minimum` to appear at the beginning of the line.

It also removes devDependencies of questionable value, as when I cloned this repo and ran `npm install`, it failed because one transitive dependency had been removed from the npm registry because it was mining Bitcoin.

### CODE REVIEW

**Comment by andrewbranch** [comment]
I figured I would make it optional, go fix everything I could, then make it required, though it would still break on PRs that have already passed checks but not yet been merged. Open to other strategies though.

**Comment by sandersn** [comment]
That sounds even better. I have to ship a new version of definitelytyped-header-parser (and I think dtslint?) for it to take effect anyway. I'll merge it now so I can go do that.

**Comment by sandersn** [comment]
3.8.2 is published. I'll update dependents shortly and report back.

**Comment by andrewbranch** [comment]
Thanks!

**Comment by sandersn** [comment]
All right, here are the new versions:

* definitelytyped-header-parser: 3.8.2
* dts-critic: 2.2.4
* dtslint: 2.0.3
* types-publisher: :woman_shrugging:

**Pull request merged**
